### ISSUE TITLE
Using ElFinder file manager to Pick up a file back occure error

### ISSUE THREAD

**Issue by polinwei** [Dominus77/yii2-tinymce-widget#1]
Hi:
When I pick up a image or file , I got a error message as below. Any suggestion? thanks
Error in `getFileCallback`.
parent.tinymce.activeEditor.windowManager.getParams(...).setUrl is not a function

**Comment by Dominus77** [comment]
Hi!
This error is caused by updating TinyMCE to version 4.6.7. To correct the error, I temporarily fixed the version of TinyMCE on 4.6.6. Perform the `composer update` . This will update the widget yii2-tinymce-widget to version 1.2.4
Thank you!

**Comment by polinwei** [comment]
It is back to normal. Thanks a lot!!
