### ISSUE TITLE
Do you plan to include the plugs for "code syntax highlighter" ?

### ISSUE THREAD

**Issue by polinwei** [Dominus77/yii2-tinymce-widget#5]
Hi Sir:
Do you plan to include the plugs for "code syntax highlighter" ?

Ref:
http://alexgorbatchev.com/SyntaxHighlighter/

**Comment by Dominus77** [comment]
Look it up: [https://www.tinymce.com/docs/plugins/codesample/](https://www.tinymce.com/docs/plugins/codesample/)
Not a bad plug-in and do not invent anything)

```
'clientOptions' => [
    //...
    'codesample_languages' => [
        ['text' => 'PHP', 'value' => 'php'],
        //...
    ],
    'codesample_content_css' => '/css/prism.css',
    //...
],
```

**Comment by polinwei** [comment]
If I want show the line number? How to configure?


http://prismjs.com/plugins/line-numbers

**Comment by Dominus77** [comment]
This already applies to the settings of the TinyMCE itself, you need to look at the documentation.

**Comment by polinwei** [comment]
I following the http://archive.tinymce.com/forum/viewtopic.php?id=33335 & http://lab.nomadonweb.com/en/sh4tinymce. I can using SH4TinyMCE - code Editor , after saved . I did not see the line numbers.

**Comment by Dominus77** [comment]
Yes, I saw this topic.
Line numbers are formed using js. TinyMCE does not support running scripts inside its frame for security purposes. You can connect only CSS and numbers will be formed only on the finished page.

**Comment by Dominus77** [comment]
Theoretically, you can try to screw SyntaxHighlighter in the TinyMCE itself and when inserting the code it will generate line numbers. This option is relevant if you do not plan to update TinyMCE.

TinyMCE will have to be downloaded to a separate folder and connected independently but not in the vendor folder.

**Comment by Dominus77** [comment]
Or else as an option, write a plug-in that, before inserting the code, will run the text through itself and generate line numbers, then paste in the editor field. By the way, this solution is more suitable but also more difficult.

**Comment by polinwei** [comment]
Yes , It is more difficult. I just a normal user...  ^^|||

**Comment by Dominus77** [comment]
In general, then having studied the documentation for TinyMCE is not very difficult)
[https://www.tinymce.com/docs/advanced/creating-a-plugin/](https://www.tinymce.com/docs/advanced/creating-a-plugin/)

**Comment by polinwei** [comment]
I find the document : https://bar-data.com/blog/yii2/example-use-syntaxhighlighter-in-yii2 
But I don't know what he say? It seems it will be workable.

**Comment by Dominus77** [comment]
[https://lab.nomadonweb.com/en/sh4tinymce/demo](https://lab.nomadonweb.com/en/sh4tinymce/demo)
Link to the demo. As you can see, there are no line numbers in the editor, only the code, and the result on the right. sh4tinymce only wraps the code in tags and puts the necessary brushes for SyntaxHighlighter.

**Comment by Dominus77** [comment]
In general, why do you need line numbers in the editor itself?)
For an approximate viewing, you can connect css this is enough, and the full version with numbers is displayed on the finished page.

**Comment by polinwei** [comment]
Sorry, This is my fault, I did not make it clear. I don't need line numbers in the editor itself. I can not see the line number in finished page.

**Comment by polinwei** [comment]
It is my way to show content " 'content:html'" as below    


`<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'content:html',
            'tags:ntext',            
            ['label'=>'status',
             'value'=>$model->status0->name,
            ],            
            ['attribute' =>'create_time',
             'value' => date('Y-m-d H:i:s',$model->create_time),
    		],
        	['attribute' =>'update_time',        	
        	 'format' => ['datetime', 'php:Y-m-d H:i:s']
        	],
            ['attribute' => 'author_id',
             'value' => $model->author->nickname,
    		]
        ],
    		'template'=>'<tr><th style="width:120px;">{label}</th><td>{value}</td></tr>',
    		'options' => ['class' => 'table table-striped table-bordered detail-view'],
    ]) ?>`

**Comment by Dominus77** [comment]
[https://github.com/Dominus77/SyntaxHighlighter](https://github.com/Dominus77/SyntaxHighlighter)

**Comment by Dominus77** [comment]
When outputting content, you should output the code framed by such tags
[https://github.com/Dominus77/example/blob/344a8638c0742cff81c6e6ec3299778a01411d37/frontend/views/site/view.php#L12](https://github.com/Dominus77/example/blob/344a8638c0742cff81c6e6ec3299778a01411d37/frontend/views/site/view.php#L12)

**Comment by Dominus77** [comment]
How do I organize a backlight on a similar page:
[https://github.com/Dominus77/example/blob/master/frontend/views/site/view2.php](https://github.com/Dominus77/example/blob/master/frontend/views/site/view2.php)

**Comment by polinwei** [comment]
Excellent !! I really want to learn how to write...
