### ISSUE TITLE
Please exclude fortawesome/font-awesome in composer require

### ISSUE THREAD

**Issue by adiramardiani** [Dominus77/yii2-tinymce-widget#6]
First, this is great tiny mce yii2 plugin, documentation, and integration with MihailDev/yii2-elfinder make this widgetamazing

But depending this plugin for something who always don't use it, is have some issue.

For example, in some project not use fontawesome v4, but v5, this plugin breaking my dependency cause same repo, but not same version, yes we can solve this with many way, but it's not make sense to create some effort with this issue

I think the best way is keeping this support for fontawesome plugin, but no need require fontawesome in composer, you can use cdn if needed _(or use content_css like you show in usage example)_ in [plugin config](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/tree/master#instructions)
`content_css: 'https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'`
or require fontawesome v4 in composer by your self

Thanks, just my opinion

**Comment by Dominus77** [comment]
Hello @adiramardiani! Thanks for contacting. Please install the widget from the dev-master branch
```
php composer.phar require dominus77/yii2-tinymce-widget "dev-master"
```
or add
```
"dominus77/yii2-tinymce-widget": "dev-master"
```
In this version, the dependency is removed, but the plug-in support remains.
https://github.com/Dominus77/yii2-tinymce-widget#plugin-fontawesome

**Comment by adiramardiani** [comment]
Yeah, you're the best @Dominus77
Listen any input and have a good decision :+1:
