### ISSUE TITLE
Challenge as a widget

### ISSUE THREAD

**Issue by w4ugit** [Dominus77/yii2-tinymce-widget#7]
Can I call it as a regular widget without binding to the model?

**Comment by Dominus77** [comment]
Why without model binding?

https://github.com/Dominus77/yii2-tinymce-widget#usage

**Comment by w4ugit** [comment]
`TinyMce::widget([
                                'options' => [
                                    'rows' => 10,
                                    'placeholder' => true,
                                ],
                                'value' => 'hello',
                                'name' => 'text',
                                'language' => 'ru',
                                'clientOptions' => [
                                    'menubar' => true,
                                    'statusbar' => true,
                                    'theme' => 'modern',
                                    'skin' => 'lightgray-gradient', //charcoal, tundora, lightgray-gradient, lightgray
                                    'plugins' => [
                                        "advlist autolink lists link image charmap print preview hr anchor pagebreak placeholder",
                                        "searchreplace wordcount visualblocks visualchars code fullscreen",
                                        "insertdatetime media nonbreaking save table contextmenu directionality",
                                        "emoticons template paste textcolor colorpicker textpattern imagetools codesample toc noneditable",
                                    ],
                                    'noneditable_noneditable_class' => 'fa',
                                    'extended_valid_elements' => 'span[class|style]',
                                    'toolbar1' => "undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
                                    'toolbar2' => "print preview media | forecolor backcolor emoticons | codesample",
                                    'image_advtab' => true,
                                    'content_css' => [
                                        '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                                        '//www.tinymce.com/css/codepen.min.css',
                                    ]
                                ],
                                'fileManager' => [
                                    'class' => MihaildevElFinder::className(),
                                ]
                            ]);`

**Comment by Dominus77** [comment]
The widget can be used without a model.
https://www.yiiframework.com/doc/guide/2.0/en/structure-widgets#widgets
